server:
  port: 8082
spring:
  profiles:
    active: dev
  gson:
    serialize-nulls: true
    date-format: yyyy-MM-dd HH:mm:ss
    long-serialization-policy: string
  http:
    converters:
      preferred-json-mapper: gson
#MyBatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.szdihang.dhome.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.szdihang.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.szdihang.xxx
    #自定义SQL注入器
    #sql-injector: com.szdihang.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#热部署配置
devtools:
  livereload:
    enabled: true
  restart:
    enabled: true
    additional-exclude: views/**
logging:
  config: classpath:log/logback-spring.xml