spring:
    data:
        mongodb:
            database: dhome
            port: 27017
            host: 127.0.0.1
    datasource:
        url: jdbc:mysql://localhost:3306/dhome?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: dhome
        password: 1234567
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        hikari:
            connection-test-query: SELECT 1
            auto-commit: false
            connection-timeout: 30000
            idle-timeout: 25000
            login-timeout: 5
            max-lifetime: 30000
            read-only: false
            validation-timeout: 3000
            maximum-pool-size: 15
            minimum-idle: 10
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
                useLocalSessionState: true
                rewriteBatchedStatements: true
                cacheResultSetMetadata: true
                cacheServerConfiguration: true
                elideSetAutoCommits: true
                maintainTimeStats: false
    aop:
        auto: true
        proxy-target-class: true